// Generated by https://quicktype.io

export interface CulturalItem {
  biblioteca_id: number;
  biblioteca_numero_coleccion: number;
  biblioteca_nombre: string;
  biblioteca_fecha_fundacion: string;
  biblioteca_adscripcion: string;
  estado_id: number;
  nom_ent: NomEnt;
  municipio_id: number;
  nom_mun: string;
  localidad_id: number;
  nom_loc: string;
  biblioteca_calle_numero: string;
  biblioteca_colonia: string;
  biblioteca_cp: number | string;
  biblioteca_telfono1: string;
  biblioteca_pagina_web: string;
  gmaps_longitud: number;
  gmaps_latitud: number;
  link_sic: string;
  fecha_mod: string;
}

export enum NomEnt {
  Aguascalientes = "Aguascalientes",
  BajaCalifornia = "Baja California",
  BajaCaliforniaSur = "Baja California Sur",
  Campeche = "Campeche",
  Chiapas = "Chiapas",
  Chihuahua = "Chihuahua",
  CiudadDeMXico = "Ciudad de M�xico",
  CoahuilaDeZaragoza = "Coahuila de Zaragoza",
  Colima = "Colima",
  Durango = "Durango",
  Guanajuato = "Guanajuato",
  Guerrero = "Guerrero",
  Hidalgo = "Hidalgo",
  Jalisco = "Jalisco",
  MXico = "M�xico",
  MichoacNDeOcampo = "Michoac�n de Ocampo",
  Morelos = "Morelos",
  Nayarit = "Nayarit",
  NuevoLEN = "Nuevo Le�n",
  Oaxaca = "Oaxaca",
  Puebla = "Puebla",
  QuerTaro = "Quer�taro",
  QuintanaRoo = "Quintana Roo",
  SANLuisPotos = "San Luis Potos�",
  Sinaloa = "Sinaloa",
  Sonora = "Sonora",
  Tabasco = "Tabasco",
  Tamaulipas = "Tamaulipas",
  Tlaxcala = "Tlaxcala",
  VeracruzDeIgnacioDeLaLlave = "Veracruz de Ignacio de la Llave",
  YucatN = "Yucat�n",
  Zacatecas = "Zacatecas",
}
